tryber/sd-07-project-recipes-app

src/App.js
=> [Group 29] organizaçao inicial

src/App.js, src/context/Provider.js, src/context/recipesContext.js, src/index.js, src/pages/Bebidas.js, src/pages/Comidas.js, src/pages/DetalhesBebidas.js, src/pages/DetalhesComidas.js, src/pages/Explorar.js, src/pages/ExplorarBebidas.js, src/pages/ExplorarBebidasIngredientes.js, src/pages/ExplorarComidas.js, src/pages/ExplorarComidasArea.js, src/pages/ExplorarComidasIngredientes.js, src/pages/Login.js, src/pages/Perfil.js, src/pages/ProcessoBebidas.js, src/pages/ProcessoComidas.js, src/pages/ReceitasFavoritas.js, src/pages/ReceitasFeitas.js
só foi feita as estruturas inciais
=> estruturas iniciais

src/App.js, src/components/Header.js, src/components/index.js, src/context/FoodAppContext.js, src/context/Provider.js, src/services/index.js
Criacao da estrutura de pastas do projeto
=> [Group 17] Arquitetura do Projeto

cypress/integration/login_spec.js, package-lock.json, src/App.js, src/Comidas.js, src/Login.js
=> Requisito 2, 3 e 4

src/App.js, src/context/Provider.js, src/pages/Login/index.js
criação dos inputs e button, com os estados de cada input.
=> [ GRUPO 32 ] RQ1, 2 e 3 - login

package-lock.json, src/pages/Login.js
=> [main-group-35] Requisitos 2,3,4,5,6,7,8 - Tela de Login

src/Components/Header.js, src/Pages/DrinkPage.js, src/Pages/ExploreDrinkByIngredients.js, src/Pages/ExploreDrinkPage.js, src/Pages/ExploreFoodByIngredients.js, src/Pages/ExploreFoodByRegion.js, src/Pages/ExploreFoodPage.js, src/Pages/ExplorePage.js, src/Pages/FoodPage.js, src/Pages/ProfilePage.js, src/Pages/RecipesFavPage.js, src/Pages/RecipesMadePage.js
Criação do componente header, foi adicionado em algumas páginas.
=> feat: add header

cypress/integration/login_spec.js, package-lock.json, package.json, src/App.js, src/Routes.js, src/actions/index.js, src/index.js, src/pages/Login.js, src/reducers/index.js, src/store/index.js
=> Requisito 2 Cypress ok Link ok

src/App.css, src/App.js, src/pages/Bebidas.jsx, src/pages/Comidas.jsx
=> [main-group-12] Tela Principal de receitas

package-lock.json, src/App.js, src/index.js, src/pages/Explore.jsx, src/pages/ExploreIngredients.jsx, src/pages/InitialExplore.jsx, src/pages/index.js
#########################
- Feitos requisitos 67 ao 73;
- Criadas duas páginas;
=> [GROUP 12] Tela de explorar

cypress/integration/header_spec.js, src/Pages/ExploreFoodByIngredients.js, src/Routes.js
Resolvido o problema do requisito 10, tava quebrando porque a ordem dos Route estava errada, logo ele mantinha o header do primeiro caminho e quebrava o teste. Também teve em uma página um erro de digitação no título da página que foi resolvido.
=> Main group 33 fix header and links

src/components/Header.css, src/components/Header.js, src/components/Header.jsx
Criação do Componente Header com: link para o perfil, lógica de exibir a barra de busca e estilização.
=> [Group 17] Header

cypress/integration/login_spec.js, package-lock.json, src/App.js, src/App.test.js, src/context/RecipesProvider.jsx, src/context/index.js, src/pages/Login/index.jsx, src/renderWithRouter.js, src/routes.js
#Criação dos Testes da Pagina de Login
=> Pagina Login, testes pagina login e criaçao da rota de Login

package-lock.json, package.json, src/components/index.js, src/pages/index.js, src/store/ducks/initialState.js, src/store/ducks/login/actions.js, src/store/ducks/login/index.js, src/store/ducks/login/types.js, src/store/ducks/receitasDeBebidas/actions.js, src/store/ducks/receitasDeBebidas/index.js, src/store/ducks/receitasDeBebidas/types.js, src/store/ducks/receitasDeComidas/actions.js, src/store/ducks/receitasDeComidas/index.js, src/store/ducks/receitasDeComidas/types.js, src/store/ducks/rootReducer.js, src/store/index.js
=> feat: implemented the redux ducks, pages and components pages structure

src/App.js, src/pages/Explore.jsx, src/pages/RecipeDetails.css, src/pages/RecipeDetails.jsx, src/pages/index.js
########################
- Finalizado requisito 74
- Redireciona para uma comida ou bebida aleatória ao clicar em "Me Surpreenda!"
=> [GROUP 12] - Requisito 74

src/App.js, src/pages/Drink/index.js, src/pages/Explore/index.js, src/pages/Food/index.js, src/pages/Login/index.js, src/pages/Perfil/index.js, src/pages/index.js, src/routes.js
- Configuração inicial de páginas;
- Estrutura de arquivos;
- Organização de rotas;
=> [Group 6] - Hérika Strongreen; Matheus Ambrosio; Murilo Pereira; Pablo Pessanha

src/components/Footer.js
componente de menu inferior criado
=> Main group 23 menu inferior

package-lock.json, src/components/TelaExplorar.js, src/pages/Explorar.js
O que será verificado:
```
- Tem os data-testids explore-food e explore-drinks.
```
Verifica se o atributo `data-testid="explore-food"` possui o texto "Explorar Comidas" e se o `data-testid="explore-drinks"` possui o texto "Explorar Bebidas".
O que será verificado:
```
- O nomes dos botões devem ser "Explorar Comidas" e "Explorar Bebidas"
```
O que será verificado:
```
- Ao clicar no botão "Explorar Comidas" a rota muda para a página de explorar comidas;
- Ao clicar no botão "Explorar Bebidas" a rota muda para a página de explorar bebidas.
=> Requisitos 67-68-69 tela explorar, botões, e navegação

.eslintrc.json, README.md, src/App.js, src/context/Provider.jsx, src/context/RecipesContext.jsx, src/index.js, src/pages/Foods.jsx, src/pages/Login.jsx
#O que foi feito?
* Tela de Login;
=> [main-group-7] Requisito 2,3, 4 e 5

cypress/integration/login_spec.js, src/pages/Login.js
=> Main group 22 requisitos 3 4 5 6 7 8

cypress/integration/footer_spec.js, src/Components/Footer.css, src/Components/Footer.js, src/Pages/DrinkPage.js, src/Pages/ExploreDrinkByIngredients.js, src/Pages/ExploreDrinkPage.js, src/Pages/ExploreFoodByIngredients.js, src/Pages/ExploreFoodByRegion.js, src/Pages/ExploreFoodPage.js, src/Pages/ExplorePage.js, src/Pages/FoodPage.js, src/Pages/ProfilePage.js
Foi criado o componente para cumprir os requisitos do 19 ao 24 dedicados a realização do Footer (menu inferior).
=> [Grupo 33] - Footer (req. 19, 20, 21, 22, 23 e 24)

cypress/integration/footer_spec.js, src/App.css, src/components/Footer/index.jsx, src/components/index.js, src/pages/DoneRecipes/index.jsx, src/pages/DrinkIngredients/index.jsx, src/pages/Explore/index.jsx, src/pages/ExploreDrinks/index.jsx, src/pages/ExploreFoods/index.jsx, src/pages/FavoritesRecipes/index.jsx, src/pages/FoodArea/index.jsx, src/pages/FoodIngredients/index.jsx, src/pages/MainDrink/index.jsx, src/pages/MainFood/index.jsx, src/pages/Profile/index.jsx
=> [Main group 24 ] Requisitos do Footer (19 a 24)

.eslintrc.json, README.md, package-lock.json, src/components/LoginForm.js, src/pages/Login/index.js
Iniciando o projeto começando pela tela de login
=> [Main group 6] [Tela de Login]

src/App.js, src/components/BottomMenu/index.js, src/components/index.js, src/context/Provider.js, src/context/RecipesContext.js, src/pages/index.js, src/services/RequestAPI.js, src/services/localStorage.js
Escolha técnica: Redux ou Context API
Criar estrutura de pastas e arquivos.
Criar um arquivo para requisições de API. (A ideia é importar, esse arquivo de funções de requisição para centralizar no app funções que serão usadas em diversos lugares)
=> [Grupo 11] criando estrutura do projeto

src/components/Loading.jsx, src/components/index.js, src/pages/Bebidas.jsx, src/pages/Comidas.jsx, src/pages/ExploreIngredients.jsx, src/pages/RecipeDetails.jsx
Finalizados requisitos 75, 76 e 77.
=> [GROUP 12] Tela de explorar ingredientes

cypress/integration/profile_spec.js, src/Components/Profile.js, src/Pages/ProfilePage.js
Feitos os requisitos referentes a página de perfil.
=> [Group 33] Profile Page - requisitos 82, 83, 84, 85, 86 e 87

src/App.js, src/components/Header.jsx, src/context/Provider.jsx, src/pages/Drinks.jsx, src/pages/Explorer.jsx, src/pages/Foods.jsx, src/pages/IngredientsDrinks.jsx, src/pages/IngredientsFoods.jsx, src/pages/Login.jsx, src/pages/OriginFoods.jsx, src/pages/Profile.jsx, src/pages/RecipesDone.jsx, src/pages/RecipesFavorites.jsx, src/services/localStorage.js
#O que foi feito?
* O componente Header e as telas que ele irá renderizar.
=> [main-group-7] Requisito 9 - Header

src/pages/Login.jsx
* Lógica para salvar no localStorage.
=> [Main-group-7] req6

src/components/Header.js, src/components/SearchBar.js, src/pages/Bebidas.js, src/pages/Explorar.js, src/pages/ExplorarBebidas.js, src/pages/ExplorarComidas.js, src/pages/ExplorarComidasArea.js, src/pages/Ingredientes.js, src/pages/MainRecipes.js
Adicionada a página de explorar e adicionado o footer em todas as páginas.
=> [Main group 2] Explorar

src/actions/index.js, src/components/DrinksRecipes.js, src/components/MealRecipes.js, src/pages/Drinks.js, src/pages/Food.js, src/reducers/index.js, src/reducers/recipes.js
=> Tela de Receitas Principal- requisitos 25 e 26

package-lock.json, src/components/Footer.js, src/css/footer.css, src/pages/DrinkExplore.js, src/pages/DrinkIngredients.js, src/pages/Drinks.js, src/pages/Explore.js, src/pages/Food.js, src/pages/FoodArea.js, src/pages/FoodExplore.js, src/pages/FoodIngredients.js, src/pages/Profile.js
Desenvolvido o componente Footer que ficará visível no rodapé de algumas páginas
=> [Main group 19] Footer

cypress/integration/header_search_bar_spec.js, src/App.js, src/Components/Card.js, src/Components/Header.js, src/Components/SearchBar.js, src/Pages/DrinkPage.js, src/Pages/FoodPage.js, src/context/RecipesContext.js, src/context/RecipesContextProvider.js, src/services/recipesApi.js
Requisitos da feature Search Bar.
=> [Group 33] - feat: Search Bar - Requirements 13, 14, 15, 16, 17, 18

src/components/CustomCardDrink.jsx, src/components/CustomCardFood.jsx, src/components/CustomCartegory.jsx, src/components/CustomSearchBar.jsx, src/components/index.js, src/pages/Drinks.jsx, src/pages/Foods.jsx, src/redux/actions/drinkRecipesAction.js, src/redux/actions/foodRecipesAction.js, src/redux/actions/index.js, src/redux/reducer/drinkRecipesReducer.js, src/redux/reducer/foodRecipesReducer.js, src/services/drinkApi.js, src/services/foodApi.js, src/services/index.js
Requisitos 25, 26, 27, 29, 30 + atualizações das branchs  do aurelio e do marcelo
=> Main group 18 requisitos da tela principal

cypress/integration/footer_spec.js, cypress/integration/login_spec.js, cypress/integration/profile_spec.js, cypress/integration/recipe_detail_spec.js, cypress/integration/recipe_in_progress_spec.js, cypress/integration/recipes_list_spec.js, cypress/integration/test_coverage_spec.js, src/App.css, src/App.js, src/components/MenuInferior.jsx, src/pages/Foods.jsx
=> [Main group 9] - Menu inferior

cypress/integration/explore_spec.js, src/Pages/ExplorePage.js
=> [Group 33] feat: explore page - requirements 67, 68, 69

.eslintrc.json, README.md, src/App.js, src/components/Loding/index.js, src/components/MenuInferior/index.js, src/pages/TelaDeLogin/index.js, src/pages/TelaPrincipalReceitasBebidas/index.js, src/pages/TelaPrincipalReceitasComidas/index.js, src/pages/index.js, src/routes/index.js
Rotas criadas segundo as paginas agora so criar e testar os componentes nas páginas
=> Main group 15 rotas

src/App.js, src/Components/CardsDrinks.js, src/Components/CardsFood.js, src/Components/CategoriesDrinks.js, src/Components/CategoriesFood.js, src/context/Provider.js, src/index.css, src/pages/Bebidas.js, src/pages/Comidas.js
….Cards clicáveis + redirecionamento para pagina de detalhes + filtros por categorias...
=> [GRUPO - 35] - Pagina de Principal

cypress/integration/recipes_list_spec.js, src/Components/Card.js, src/Components/Header.js, src/Components/Profile.js, src/Pages/DrinkPage.js, src/Pages/ExploreFoodByRegion.js, src/Pages/FoodPage.js, src/Routes.js, src/context/RecipesContextProvider.js
Criada página principal de Comidas, bebidas. Corrigido icone de busca nos Headers adequados e feito lógica condicional na página de perfil para o teste não quebrar ao acessar a página.
=> Main group 33 feat main pages

src/App.js, src/pages/ExploreArea.jsx, src/pages/index.js
Finalizados requisitos 78 à 81
=> [GROUP 12] - Tela de explorar por área

src/pages/Profile.jsx
Requisitos de perfil de usuário criados com sucesso
=> Requisitos 82 a 87 resolvidos

src/App.js, src/components/Footer.css, src/components/Footer.jsx, src/pages/Explorer.jsx, src/pages/ExplorerDrinks.jsx, src/pages/ExplorerFoods.jsx, src/pages/Foods.jsx, src/pages/IngredientsDrinks.jsx, src/pages/IngredientsFoods.jsx, src/pages/OriginFoods.jsx, src/pages/Profile.jsx
#O que foi feito?
*Footer das telas.
=> [Main-group-7] Requisito 19 footer

src/components/CustomCardSuggested.jsx, src/components/CustomSearchBar.jsx, src/pages/Foods.jsx, src/pages/RecipeDetails.jsx, src/services/drinkApi.js, src/services/foodApi.js, src/services/index.js
Feitos requistos 33, 34, 35, 36(ainda em andamento) e merge.
=> Main group 18 - Tela de detalhes

src/services/localStorage.js, src/services/requestDrink.js, src/services/requestFood.js
Create and implement services - API requests functions - for entire project.
=> implement services for entire project

cypress/integration/explore_drinks_or_meals_spec.js, src/Pages/DrinkPage.js, src/Pages/ExploreDrinkPage.js, src/Pages/ExploreFoodPage.js, src/services/recipesApi.js
Requisitos da feature Explorar Comidas ou Bebidas.
=> [Group 33] feat: Explore Meals or Drinks - Requirements: 70, 71, 72, 73, 74

package.json, src/App.js, src/App.test.js, src/components/Login.jsx, src/context/CoffeeAndCodeContext.jsx, src/context/Provider.jsx, src/index.js, src/pages/Home.jsx, src/tests/Login.test.js, src/tests/renderWithRouter.js
- Home renderizando componente Login
- Componente Login com inputs para email e senha
- Botão de Entrar
- Interação para verificar email e senha validos
- Ativação do botão quando email e senha forem validados
- Testes simples para verificar a presença de inputs e button no componente Login
- Context e Provider
- Estados para email e senha
=> Main group 28 pagina de login requisito 2

src/context/GlobalProvider.js, src/data/dataLogin.js, src/data/detailRecipes.js, src/data/index.js, src/hooks/useFetch.js, src/pages/FoodDetails.jsx, src/pages/Login.jsx
Criação de estrutura inicial para tela de detalhes de receita.
=> [main-group-20][requisito 33] tela de detalhes de receita

src/Components/SearchbarComp.js, src/pages/Drink/index.js, src/pages/Food/index.js, src/providers/DrinkProvider.js, src/providers/FoodProvider.js, src/services/categoriesDrink.js, src/services/categoriesFood.js
Foi chatinho esse 27 e depois tenho que organizar de modo melhor esta requisição pois neste useEffect não ta legal..
--- EDIT ---
- Alterado a requisição pra construir os botões, por um array com as frases exigidas pelo requisito, tirando a necessidade da requisição no `useEffect`;
- Reaproveitado os novos arquivos de requisição, para a requisição 28;
- Para o requisito 29, foi feito a lógica de `booleanos` em objetos, para retirar ou colocar o filtro novamente, sempre fazendo as requisições novamente. (fiz dessa forma pra não alterar muito o código, talvez armazenar os dados fizesse com que tivesse mais alterações, visei fazer o menos possivel.)
=> nao eh o codigo mais bonito do mundo, mas passou! kk

package-lock.json, src/App.js, src/pages/CocktailRecipeDetails.js, src/pages/MealRecipeDetails.js, src/styles/recipeDetails.css
Foram criados as duas páginas que exibe os detalhes da comida ou da bebida. Eu fiz rotas e informações fakes apenas para passar no teste, pois necessitava da parte das chamadas de API para deixar pronto de forma correta. Portanto está pronto apenas a estrutura dessas páginas, necessitando o merge das chamadas de API para alterar as informações vindas da API.
=> Req 33 - Criado a pagina de detalhes de comida e bebida

src/components/Header.js
Não me orgulho da solução mas podemos refatorar no final.
=> [Group 19] Requisito 15 finalizado

src/pages/ExploreDrinks.js, src/pages/ExploreFoods.js, src/styles/Explore.css, src/tests/explore_drinks_or_meals_spec.test.js
Referente aos requisitos do 70 ao 73, foram realizados: adição dos elementos, links e testes unitários.
=> [Group 17] Explorar Bebidas e Comidas

src/components/MainCards.js, src/components/MainDrinkCards.js, src/context/RecipesProvider.js, src/pages/MainDrinks.js, src/pages/MainRecipes.js, src/services/drinkApiFunctions.js, src/services/foodApiFunctions.js
o que foi feito: 
25 - Implemente os elementos da tela principal de receitas respeitando os atributos descritos no protótipo
26 - Carregue as 12 primeiras receitas de comidas ou bebidas, uma em cada card
27 - Implemente os botões de categoria para serem utilizados como filtro
28 - Implemente o filtro das receitas através da API ao clicar no filtro de categoria
29 - Implemente o filtro como um toggle, que se for selecionado de novo, o app deve retornar as receitas sem nenhum filtro
31 - Desenvolva o filtro de categorias com a opção de filtrar por todas as categorias
32 - Redirecione a pessoa usuária, ao clicar no card, para a tela de detalhes, que deve mudar a rota e conter o id da receita na URL
=> Main group 21 main recipes

src/pages/Profile.js
Requisitos 82, 83, 84, 85, 86 e 87 ESlint ok Cypress ok. Grupo 22.
=> requisitos 82 a 87 Eslint ok Cypress ok

src/pages/Foods.jsx, src/redux/reducer/foodRecipesReducer.js
arrumando para passar o 28 e arrumando para voltar para todas as categorias
=> Main group 18 requisitos da tela principal - arrumando para passar o 28 e arrumando para voltar para todas as categorias

src/Components/PerfilProfile.js, src/pages/Perfil/index.js
Tela de Perfil completa e passando no cypress
=> [Main group 6] [tela de perfil]

src/Routes.js, src/actions/index.js, src/actions/mainpage.js, src/pages/CocktailDetails.js, src/pages/Cocktails.js, src/pages/MealDetails.js, src/pages/Meals.js, src/reducers/index.js, src/reducers/mainpage.js
Implementando tela principal
Requisitos 25 a 32
=> [Main group 22] Tela Principal

package.json, src/App.js, src/App.test.js, src/components/Login.jsx, src/context/CoffeeAndCodeContext.jsx, src/context/Provider.jsx, src/index.js, src/pages/Comidas.jsx, src/pages/Food.jsx, src/pages/Home.jsx, src/tests/Login.test.js, src/tests/renderWithRouter.js
- Adições e correções nos testes
- Chamadas do services/localStorage
- Criação do componente Comidas
_A rota e o componente foram criadas com os nomes em português para que pudesse passar nos testes_
=> Main group 28 pagina de login local storage

src/App.js, src/components/CustomButtonFavorite.jsx, src/components/CustomButtonShare.jsx, src/components/CustomCardSuggested.jsx, src/components/CustomDetailsButton.jsx, src/components/CustomDetailsIngredients.jsx, src/components/index.js, src/pages/Foods.jsx, src/pages/Login.jsx, src/pages/RecipeDetails.jsx
Feito o restante dos requisitos da tela de detalhes.
=> Main group 18 tela de detalhes continuação

package-lock.json, package.json, src/App.js, src/pages/DetalhesBebidas.js, src/pages/DetalhesComidas.js
Detalhes de importação da lib-Slick
=> Detalhes de importaçao da lib-Slick

src/pages/TelaPrincipalReceitasBebidas/index.js, src/pages/TelaPrincipalReceitasComidas/index.js
problema em achar rota  de card resolvido
=> Main group 15 correcao

cypress/integration/header_spec.js, cypress/integration/profile_spec.js, src/components/ProfileDetails.js, src/css/profile.css, src/pages/Profile.js
=> [Main Group 19] Profile Page

src/App.js, src/pages/DrinkDetails.js, src/pages/DrinkIngredient.js, src/pages/Explore.js, src/pages/ExploreDrink.js, src/pages/ExploreFood.js, src/pages/FoodArea.js, src/pages/FoodDetails.js, src/pages/FoodIngredient.js, src/services/helpers.js, src/style/recipeDetail.css
Tela de explorar|Tela de explorar bebidas/comidas|Tela de explorar ingredients
=> [Main group 29] Tela de explorar|Tela de explorar bebidas/comidas|Tela de explorar ingredients

src/App.js, src/components/Footer/Footer.test.js, src/components/Footer/style.css, src/pages/MainPage/index.js, src/pages/Profile/index.js
82 - Implemente os elementos da a tela de perfil respeitando os atributos descritos no protótipo
83 - Implemente a solução de maneira que o e-mail da pessoa usuária deve estar visível
84 - Implemente 3 botões: um de nome "Receitas Feitas", um de nome "Receitas Favoritas" e um de nome "Sair"
85 - Redirecione a pessoa usuária que, ao clicar no botão de "Receitas Favoritas", a rota deve mudar para a tela de receitas favoritas
86 - Redirecione a pessoa usuária que, ao clicar no botão de "Receitas Feitas", a rota deve mudar para a tela de receitas feitas
87 - Redirecione a pessoa usuária que, ao clicar no botão de "Sair", o localStorage deve ser limpo e a rota deve mudar para a tela de login
=> [Grupo 11] tela de perfil pronta

src/actions/index.js, src/actions/mainpage.js, src/pages/Cocktails.js, src/pages/ExploreCocktailsIngredients.js, src/pages/ExploreMealsIngredients.js, src/pages/Meals.js, src/reducers/mainpage.js, src/services/cocktailAPI.js, src/services/mealAPI.js
Implementa página que permite explorar receitas por ingrediente.
Requisitos 75 a 77
=> [Main Group 22] Explorar Ingredientes

src/Context/RecipesProvider.jsx, src/Context/index.js, src/components/Header/HeaderNoSearch.jsx, src/components/Header/index.jsx, src/components/Header/style.css, src/components/RecipeDetails/index.jsx, src/components/RecipesMade/index.jsx, src/components/RecipesMade/style.css, src/pages/RecipesMadePage/index.jsx
=> Tela receitas feitas

src/Context/Hooks/useLocalStorage.js, src/Context/RecipesProvider.jsx, src/Context/index.js, src/components/FavoriteRecipes/index.jsx, src/components/FavoriteRecipes/style.css, src/components/Header/HeaderNoSearch.jsx, src/components/Header/index.jsx, src/components/Header/style.css, src/components/RecipeDetails/index.jsx, src/components/RecipesMade/index.jsx, src/components/RecipesMade/style.css, src/pages/RecipesFavoritesPage/index.jsx, src/pages/RecipesMadePage/index.jsx
=> Tela receitas favoritas

src/components/ExploreButtons/index.jsx, src/pages/ExplorePage/index.jsx
=> Tela explorar

src/Context/RecipesProvider.jsx, src/components/ExploreFoodButtons/index.jsx, src/pages/ExploreDrinkPage/index.jsx, src/pages/ExploreFoodPage/index.jsx
=> Tela explorar comidas bebidas

cypress/integration/explore_by_area_spec.js, cypress/integration/explore_by_ingredient_spec.js, src/Components/ButtonsShareAndFavDrinks.js, src/Components/ButtonsShareAndFavFood.js, src/Components/Card.js, src/Components/DetailsDrink.js, src/Components/DetailsFood.js, src/Components/NotFound.js, src/Components/RecomendationCards.js, src/Pages/DetailDrinkPage.js, src/Pages/DetailFoodPage.js, src/Pages/DrinkPage.js, src/Pages/ExploreDrinkByIngredients.js, src/Pages/ExploreFoodByIngredients.js, src/Pages/ExploreFoodByRegion.js, src/Pages/FoodPage.js, src/Routes.js
Requisitos da tela de filtro por regiões.
=> [Group 33] Feat: Explore by Regions - requirements 78, 79, 80, 81

cypress/integration/explore_by_ingredient_spec.js, src/Components/ButtonsShareAndFavDrinks.js, src/Components/ButtonsShareAndFavFood.js, src/Components/Card.js, src/Components/DetailsDrink.js, src/Components/DetailsFood.js, src/Components/RecomendationCards.js, src/Pages/DetailDrinkPage.js, src/Pages/DetailFoodPage.js, src/Pages/DrinkPage.js, src/Pages/ExploreDrinkByIngredients.js, src/Pages/ExploreFoodByIngredients.js, src/Pages/FoodPage.js, src/Routes.js
Cypress trava em loop infinito no teste do requisito 76.
=> Main group 33 req76 cypress bug

src/components/ExploreFoodButtons/index.jsx, src/components/Grid/index.jsx, src/components/Ingredients/index.jsx, src/components/Ingredients/style.css, src/pages/ExploreDrinkByIngredients/index.jsx, src/pages/ExploreFoodByIngredients/index.jsx, src/pages/ExploreFoodPage/index.jsx
=> Tela explorar ingredientes

src/Context/Hooks/useLocalStorage.js, src/Context/RecipesProvider.jsx, src/Context/index.js, src/Hooks/useLoadApiData.js, src/Hooks/useLocalStorage.js, src/Routes.jsx, src/components/ExploreArea/index.jsx, src/components/ExploreArea/style.css, src/components/Grid/index.jsx, src/components/Profile/index.jsx, src/pages/DrinkPage/index.jsx, src/pages/ExploreFoodByArea/index.jsx, src/pages/FoodPage/index.jsx, src/pages/ProfilePage/index.jsx
=> Tela explorar area

src/Context/RecipesProvider.jsx, src/Hooks/useLoadRecipeDetails.js, src/components/ExploreArea/index.jsx, src/components/FavoriteRecipes/index.jsx, src/components/Grid/index.jsx, src/components/Recipe/index.jsx, src/components/RecipeContainer/index.jsx, src/components/RecipeDetails/index.jsx, src/components/RecipesMade/index.jsx, src/pages/DetailDrinkPage/index.jsx, src/pages/DetailFoodPage/index.jsx, src/pages/FoodPage/index.jsx
Reorganização de alguns componentes
=> Big refactor

package-lock.json, package.json, src/App.js, src/components/Footer.jsx, src/components/Header.jsx, src/components/HeaderSearch.jsx, src/context/Provider.jsx, src/pages/Bebidas.jsx, src/pages/BebidasPorIngredientes.jsx, src/pages/Comidas.jsx, src/pages/ComidasPorIngredientes.jsx, src/pages/ComidasPorOrigem.jsx, src/pages/DetalhesBebidas.jsx, src/pages/DetalhesReceita.jsx, src/pages/Explorar.jsx, src/pages/ExplorarBebidas.jsx, src/pages/ExplorarComidas.jsx, src/pages/ExplorarOrigem.jsx, src/pages/Perfil.jsx, src/pages/ProcessoBebida.jsx, src/pages/ProcessoReceita.jsx, src/pages/ReceitasFavoritas.jsx, src/pages/ReceitasFeitas.jsx, src/styles/components/footer.css, src/tests/Footer.test.js, src/tests/Header.test.js, src/tests/HeaderSearch.test.js, src/tests/Login.test.js
- Renderização do componente Footer nas paginas indicadas pelo protótipo
- Teste do componente Footer
- Componente Footer fixado no rodapé da página
- Links redirecionando para páginas _/bebidas_ , _/explorar_ , _/comidas_
- Imagens adicionadas para os Links
=> Main group 28 footer

src/App.js, src/components/Header.jsx, src/components/HeaderSearch.jsx, src/pages/Bebidas.jsx, src/pages/BebidasPorIngredientes.jsx, src/pages/Comidas.jsx, src/pages/ComidasPorIngredientes.jsx, src/pages/ComidasPorOrigem.jsx, src/pages/DetalhesBebidas.jsx, src/pages/DetalhesReceita.jsx, src/pages/Explorar.jsx, src/pages/ExplorarBebidas.jsx, src/pages/ExplorarComidas.jsx, src/pages/ExplorarOrigem.jsx, src/pages/Perfil.jsx, src/pages/ProcessoBebida.jsx, src/pages/ProcessoReceita.jsx, src/pages/ReceitasFavoritas.jsx, src/pages/ReceitasFeitas.jsx, src/tests/Header.test.js
- Criação das pages
- Rotas setadas
- Testes para o componente Header
- Criação do componente Header
- Implementação das lógicas de funções e eventos do Header
=> Main group 28 header

src/App.css, src/App.js, src/components/RecipesCard.js, src/pages/ExplorarComidasArea.js, src/pages/Login.jsx, src/pages/NotFound.jsx, src/pages/index.js, src/tests/header.test.js
**_CSS:_**
- Removido o height e o width da classe main.
- Adicionado margin-top de 57px e margin-bottom de 40px
**_Components:_**
- RecipesCard: Adicionadas as tags do bootstrap para fazer um card.
**_Pages:_**
- Login: Adicionado autoComplete ao email e senha.
- Criada a page de Explorar comida por área (ExplorarComidasArea).
- Criada a page NotFound e sua rota.
=> [Main group 2] Tela explorar origem

src/pages/Drinks.jsx, src/pages/Foods.jsx, src/services/api.js
Carrega os 12 primeiros itens e os 5 primeiros botões com categoria, de comida e bebida
=> [main-group-7] - Requisitos 25, 26, 27, 28

src/components/HeaderSearchBar.js, src/context/RecipesProvider.js, src/pages/MainDrinks.js, src/pages/MainRecipes.js
14 - Posicione a barra logo abaixo do header e implemente 3 radio buttons: Ingrediente, Nome e Primeira letra
15 - Busque na API de comidas caso a pessoa esteja na página de comidas e na de bebidas caso esteja na de bebidas
16 - Redirecione para a tela de detalhes da receita caso apenas uma receita seja encontrada, com o ID da mesma na URL
17 - Mostre as receitas em cards caso mais de uma receita seja encontrada
18 - Exiba um alert caso nenhuma receita seja encontrada
=> Main group 21 seach bar get api

src/components/RecipeDrinkCard.jsx, src/components/RecipeFoodCard.jsx, src/pages/DoneRecipes.jsx, src/pages/Drinks.jsx, src/pages/Explore.jsx, src/pages/ExploreDrinks.jsx, src/pages/ExploreDrinksIngredients.jsx, src/pages/ExploreFoods.jsx, src/pages/ExploreFoodsArea.jsx, src/pages/ExploreFoodsIngredients.jsx, src/pages/FavoritesRecipes.jsx, src/pages/Profile.jsx
Alterando os titles do header para passar no avaliador!
=> [Main group 9] -  Arrumando header

src/components/DrinksRecipes.js, src/components/Header.js, src/components/MealRecipes.js, src/pages/Login.js
=> [Main Group 19]  - Requisito 16. 17, 18

src/components/Card/index.js, src/components/Categories/index.js, src/context/Provider.js, src/pages/Recipes/index.js, src/services/api.js, src/tests/Footer.test.js, src/tests/Login.test.js
=> Main group 4 recipes list

src/pages/CocktailsInProgress.js, src/pages/MealsInProgress.js, src/pages/Profile.js
Ajustando os requisitos 10, 11 e 21 para o avaliador. Modifica a página de perfil para o caso de o usuário não estar logado.
=> [Main Group 22] Ajuste 10 e 11

src/Components/CardsDrinks.js, src/Components/CardsFood.js, src/Components/cards.css, src/index.css, src/pages/DetalhesBebidas.js, src/pages/DetalhesComidas.js, src/pages/Login.js, src/services/functions.js, src/tests/Login.test.js, src/tests/renderWithRouter.js
Tests pagina de login, finalização da pagina de detalhes, implementação do botão de favorito
=> [GRUPO - 35] - finalização pagina de detalhes + tests login

src/App.js, src/components/IngredientsCheckbox.jsx, src/components/IngredientsInProgress.jsx, src/components/RecipeDetailsButton.jsx, src/components/RecipeDetailsHeader.jsx, src/components/RecipeDetailsIngredients.jsx, src/components/RecommendedRecipesBody.jsx, src/components/index.js, src/context/RecipeContext.js, src/pages/DoneRecipes.jsx, src/pages/RecipeDetails.css, src/pages/RecipeDetails.jsx, src/services/index.js
########################
- Tela de receitas finalizada;
Falta:
- implementar CSS;
- corrigir erros da aplicação;
=> [GROUP 12] - Tela de receitas em progresso

src/actions/index.js, src/actions/mainpage.js, src/pages/ExploreCocktailsOrigin.js, src/pages/ExploreMealsOrigin.js, src/reducers/mainpage.js, src/services/mealAPI.js
Implementa página que permite explorar receitar por área de origem.
=> [Main Group 22] Explorar Area

src/App.js, src/components/ExploreFoodIngredientCards.js, src/context/RecipesProvider.js, src/pages/Explorer.js, src/pages/ExplorerDrinks.js, src/pages/ExplorerDrinksIngredients.js, src/pages/ExplorerFood.js, src/pages/ExplorerFoodArea.js, src/pages/ExplorerFoodIngredients.js, src/pages/MainDrinks.js, src/pages/MainRecipes.js, src/pages/NotFound.js, src/services/drinkApiFunctions.js, src/services/foodApiFunctions.js
Tela de explorar
Tela de explorar por ingredientes tanto de comida quanto de bebidas
=> Main group 21 explore screen

src/components/FoodThumb/index.js, src/pages/Comidas/index.js, src/pages/ReceitasFavoritas/index.js, src/pages/ReceitasFavoritas/styles.css, src/routes/index.js, src/services/localstorage.js
* Página de receitas favoritas
=> [Group 23] - Receitas Favoritas

src/pages/Drinks.jsx, src/pages/Foods.jsx, src/pages/Profile.jsx
=> [Main group 7] Requisito 29 ao 32

cypress/integration/header_spec.js, cypress/integration/recipe_detail_spec.js, src/actions/index.js, src/components/DrinksCategoryFilter.js, src/components/DrinksRecipes.js, src/components/Loading.js, src/components/MealRecipes.js, src/components/MealsCategoryFilter.js, src/css/details.css, src/pages/DrinkInProgress.js, src/pages/Drinks.js, src/pages/Food.js, src/pages/FoodInProgress.js, src/reducers/categories.js, src/reducers/index.js
Em desenvolvimento, NÃO MERGEAR AINDA
=> [Main group 19] Food in progress (não mergear)

src/Components/inputSearch.css
=> Correção CSS

src/components/ButtonCategoriesDrink.jsx, src/components/ButtonCategoriesFood.jsx, src/components/CardsDrink.jsx, src/context/Provider.jsx, src/pages/Bebidas.jsx, src/pages/Comidas.jsx
- Criação dos componentes _ButtonCategoriesDrink_ e _ButtonCategoriesFood_
- Estruturação dos componentes.
- Chamada de Api para capturar as categorias.
- Filtragem para capturar apenas as 5 primeiras.
- Renderização dos botões de categorias.
- Lógica para renderização das receitas de acordo com a filtragem.
- Correção no componente _CardsDrink_
_**Não foram feitos testes**_
=> Main group 28 tela de receitas botoes categoria

src/components/DetailsHeader/index.js, src/components/FavoriteAndDone/index.js, src/components/ShareButton/index.js, src/components/index.js, src/pages/DoneRecipes/index.js, src/pages/FavoriteRecipes/index.js
60 - Implemente os elementos da tela de receitas favoritas (cumulativo com os atributos em comum com a tela de receitas feitas) respeitando os atributos descritos no protótipo
61 - Desenvolva a tela de maneira que, caso a receita do card seja uma comida, ela deve possuir: a foto da receita, o nome, a categoria, a area, um botão de compartilhar e um de "desfavoritar"
62 - Desenvolva a tela de maneira que, caso a receita do card seja uma bebida, ela deve possuir: a foto da receita, o nome, se é alcoólica ou não, um botão de compartilhar e um de "desfavoritar"
63 - Desenvolva a solução de maneira que o botão de compartilhar deve copiar a URL da tela de detalhes da receita para o clipboard
64 - Desenvolva a solução de maneira que o botão de "desfavoritar" deve remover a receita da lista de …
=> [Grupo 11] tela de favoritos ok

cypress/integration/recipe_detail_spec.js, src/Components/CardsDrinks.js, src/Components/CardsFood.js, src/context/Provider.js
exibição de apenas 1 card quando solicitado filtro por categorias
=> [main-group-35] - Correção do requisito 28 - 

src/App.js, src/components/CategoriesBar.js, src/components/CocktailCard.js, src/components/Header.js, src/pages/Cocktails.js, src/pages/DrinksExplorer.js, src/pages/DrinksIngredients.js, src/pages/MealsIngredients.js, src/pages/MealsOrigin.js, src/pages/Profile.js, src/reducers/cocktails.js
Criado o componente CocktailCard e a página Cocktails. Realizadas as alterações necessárias para os testes dos componentes e páginas já criadoas serem aprovados.
=> [GRUPO 34][SOLUÇÃO DOS TESTES]

src/components/FavoriteAndDone/index.js, src/pages/DoneRecipes/index.js
54 - Implemente os elementos da tela de receitas feitas respeitando os atributos descritos no protótipo
55 - Desenvolva a tela de maneira que, caso a receita do card seja uma comida, ela deve possuir: a foto da receita, o nome, a categoria, a area, a data em que a pessoa fez a receita, as 2 primeiras tags retornadas pela API e um botão de compartilhar
56 - Desenvolva a tela de maneira que, caso a receita do card seja uma bebida, ela deve possuir: a foto da receita, o nome, se é alcoólica, a data em que a pessoa fez a receita e um botão de compartilhar
57 - Desenvolva a solução de maneira que o botão de compartilhar deve copiar a URL da tela de detalhes da receita para o clipboard
58 - Implemente 2 botões que filtram as receitas por comida ou bebida e um terceiro que remove todos os …
=> [Grupo 11] tela de receitas feitas ok

src/App.css, src/components/CategorySelector.js, src/components/RecipesCard.js, src/components/RecipesList.js, src/pages/Ingredientes.js, src/pages/ReceitaBebida.js, src/pages/ReceitaComida.js
- Elaboração detalhes iniciais das páginas de bebidas e comidas
- Correção css para requisitos 14, 16, 17 e 18
- Ajuste nas chamadas da API no componente CategorySelector
=> [Grupo 2] - Página de Detalhes

src/pages/Perfil/index.js
=> requisitos

cypress/integration/recipe_detail_spec.js, src/pages/ReceitasFavoritas/index.js, src/pages/ReceitasFeitas/index.js, src/pages/ReceitasFeitas/styles.css, src/routes/index.js
=> [GROUP 23] Done Receipes

src/App.css, src/pages/ExploreCocktailsIngredients.js
Ajustando modificações que estavam quebrando os testes de requisitos que já tinham sido aprovados.
=> Main group 22 ajustes requisitos anteriores

src/pages/Profile.js, src/services/localStorageFunctions.js
* 83 - Implemente a solução de maneira que o e-mail da pessoa usuária deve estar visível;
* 87 - Redirecione a pessoa usuária que, ao clicar no botão de "Sair", o localStorage deve ser limpo e a rota deve mudar para a tela de login;
=> Commitando requisitos 83 e 87.

src/components/DoneRecipesCards.js, src/context/RecipesProvider.js, src/pages/DoneRecipes.js, src/services/localStorageFunctions.js
O que foi feito: 
A implementação da tela de receitas feitas, requisitos 54 a 59
=> Main group 21 receitas prontas

src/tests/Detalhes.test.js, src/tests/Explorar.test.js
Aqui eu adiciono o arquivo Detalhes e Explorar... esqueci de fazer uma branch pra o Explorar
=> Main group 13 test details

src/pages/Bebidas/index.js, src/pages/Explorar/ExplorarBebidas/Ingredientes/index.js
=> [GROUP 23] Requisito 77

src/components/DrinkRecom.js, src/components/FoodRecom.js, src/pages/detailsDrink.js, src/pages/detailsFood.js, src/pages/profile.js
[Group-14] Os requisitos 35, 36, 37, 38 entregues. O Requisito 39 esta passando mas precisa de uma logica e depende de outro componente.
=> Main group 14 requisito 35

src/components/MealRecipes.js, src/pages/DrinkExplore.js, src/pages/FoodExplore.js
Tela de explorar bebibas e comidas.
Requisitos  70,71,72 e 73 completos
Fazer lógica de aleatoriedade da receita a ser mostrada no "Me Surpreenda" (Requisito 74)
=> [Grupo 19] Requisitos 70,71,72 e 73 completos

src/components/FavoriteRecipesCards.js, src/context/RecipesProvider.js, src/pages/FavoriteRecipes.js
Todas as implementaçõs da tela de refeitas favoritas
=> Main group 21 favorite screen

src/App.js, src/components/RecipeDoneCard.js, src/pages/RecipesDone.js
Criada a página de receitas feitas e o componente do card de receitas feitas.
=> [GRUPO 34][RECIPES DONE PAGE]

src/App.js, src/components/FavoriteRecipeCard.js, src/components/RecipeDoneCard.js, src/pages/FavoriteRecipes.js, src/pages/RecipesDone.js
Criada a página de receitas favoritas e o componente do card de receitas favoritas.
=> [GRUPO 34][FAVORITES RECIPES PAGE]

src/components/SearchBar.js
- foi adicionando o toggle ao data test id do input, para conseguir passar no avaliador
=> [Main group 34 header erro req 12]

src/components/SearchBar.js, src/reducers/cocktails.js, src/reducers/meals.js
- fiz passar os requisitos 17 e 18 da pagina de SearchBar
=> [Main group 34 header search erro req 17 e 18]

package-lock.json, package.json, src/components/FavoriteHeart.jsx, src/context/Provider.jsx, src/pages/DetalhesBebidas.jsx, src/pages/DetalhesReceita.jsx
- Implementação da tela de detalhes para comidas e bebidas;
- Toda estruturação
- Todos data-testids
- Botão para iniciar a receita
- Alterar botão de "iniciar receita" para "continuar receita"
- Tirar o botão de iniciar receita caso a receita tenha sido concluída
- Botão para compartilhar
- Lógica do botão para compartilhar
- Adição da lib react-slick
- Implementação do carrosel
- Adição da lib react-copy-to-clipboard
- Mostrar mensagem quando clicar no botão para compartilhar
- Implementação do botão de favoritos
- Lógica do botão de favoritos
- Adição de favoritos ao localStorage
- Adição do progresso da receita ao localStorage
- Mostrar se a bebida é alcoólica ou não
- Embedar vídeo da receita de comida
- Implementação dos sugestões
- Filtragens dos ingredientes e quantidade
**_Os …
=> Main group 28 tela de detalhes de receita

src/App.js, src/components/CardsByArea.js, src/pages/DrinkArea.js, src/pages/DrinkDetails.js, src/pages/FavoriteRecipes.js, src/pages/FoodArea.js, src/pages/FoodDetails.js
tela de explorar por local de origem
=> [Main group 29] Tela de explorar por local de origem

cypress/integration/recipe_in_progress_spec.js, src/css/details.css, src/localStorage/inProgressRecipes.js, src/pages/DrinkInProgress.js, src/pages/FoodInProgress.js
=> [Main Group 19] Receita em Progresso

cypress/integration/recipe_detail_spec.js, src/components/Header/style.css, src/components/IngredientsTable/index.js, src/pages/Progress/Actions.js, src/pages/Progress/index.js, src/pages/Progress/style.css, src/services/api.js
Apareceram estes erros:
Requisito 28
1) Caso as receitas sejam de bebida e a categoria seja "Other/Unknown", deve-se carregar as 12 primeiras receitas de "Other/Unknown"
CypressError: Timed out retrying: cy.click() failed because the center of this element is hidden from view:
Requisito 41
1) Redireciona para tela de receita da comida em processo
Uncaught TypeError: Cannot read property 'strMeal' of undefined
This error originated from your application code, not from Cypress.
=> Conciliação main atual com os requisitos 47 a 53

src/App.js, src/components/ButtonStart.js, src/components/ButtonsDetailsPage.js, src/components/Recommendations.js, src/functions/DetailPages.js, src/pages/CocktailDetails.js, src/pages/CocktailsInProgress.js, src/pages/MealDetails.js, src/pages/MealsInProgress.js
=> Main group 22 requisitos 39 e 40

src/pages/ExplorarBebidas.jsx, src/pages/ExplorarComidas.jsx
- Implementação da tela de explorar de comidas e bebidas
- redirecionamentos
- requisição de api para receita aleatória
**_Os testes não foram feitos_**
=> Implementação dos botãos de explorar

src/pages/BebidasPorIngredientes.jsx, src/pages/ComidasPorIngredientes.jsx
- Implementação da page _comidasPorIngredientes_
- Implementação da page _bebidasPorIngredientes_
- Atualização dos estados CardFood e CardDrink quando clicado em algum ingrediente.
=> Main group 28 tela de explorar ingredientes

src/App.js, src/components/Card/index.js, src/pages/ExploreByArea/index.js, src/pages/ExploreByArea/style.css, src/pages/NotFound/index.js, src/pages/RecipesInProgress/index.js, src/pages/RecipesInProgress/style.css, src/pages/index.js
78 - Implemente os elementos da tela de explorar por local de origem respeitando os atributos descritos no protótipo
79 - Desenvolva as mesmas especificações da tela de receitas principal, com a diferença de que os filtros de categoria são substituídos por um dropdown
80 - Implemente o dropdown de maneira que devem estar disponíveis todas as áreas retornadas da API, incluindo a opção "All", que retorna as receitas sem nenhum filtro
81 - Implemente a rota que deve ser apenas /explorar/comidas/area
=> [Grupo 11] tela de explorar por origem ok

src/pages/TelaDetalheBebida/index.js, src/pages/TelaDetalheComida/index.js
=> Main group 15 requirement 43

src/components/Recomendations/Item.js, src/components/Recomendations/index.js, src/components/Recomendations/style.css, src/components/Recomendations/styles.css, src/pages/RecipeDetails/index.js
Removi o carrossel, o teste não identificava a troca de imagens
=> Removi o carrossel

cypress/integration/done_recipes_spec.js, src/pages/DoneRecipe.js
=> Requisito 59

src/App.css, src/App.js, src/pages/CheckBoxProgress.js, src/pages/DrinkInProgress.js, src/pages/FoodInProgress.js, src/pages/Login.js
=> [GRUPO 29] Checkbox Progress

src/pages/FoodDetails.js, src/pages/Login.js, src/services/helpers.js, src/style/login.css
=> [Main group 29] style tela de login

src/components/ButtonsFavoritePage.js, src/pages/CocktailDetails.js, src/pages/FavoriteRecipes.js, src/pages/MealDetails.js
Página favoritos 
ESLint ok
Cypress ok
=> Main group 22 favorite page

src/images/packageDelivery.svg, src/pages/Login.css, src/pages/Login.jsx
##############################
- Feita estilização do logo
=> [GROUP 12] - Estilização do logo

src/pages/DrinkExplore.js, src/pages/Explore.js, src/pages/FoodExplore.js
Estilização dos botões na tela de Explorar
=> [Main Group 19] Estilizacao dos botões na tela de Explorar

src/components/RecomendationCardDrink/index.js, src/components/RecomendationCardMeal/index.js, src/pages/TelaDetalheBebida/index.js, src/pages/TelaDetalheComida/index.js, src/services/localStorageAPI/getStorage.js, src/services/localStorageAPI/setStorage.js
=> Main group 15 requirement 46

src/components/Footer/index.js, src/components/RecipeCard/index.js, src/components/RecipeCardList/index.js, src/components/RecipeCategoryFilter/index.js, src/components/RecipeDoneFavCard/index.js, src/components/RecipeDoneFavCard/styles.js, src/components/RecipeFilter/index.js, src/components/SearchBar/index.js, src/pages/Home/index.js, src/pages/Profile/index.js, src/pages/RecipeDone/index.js, src/pages/RecipeExplore/index.js, src/pages/RecipeExploreArea/index.js, src/pages/RecipeExploreByIngredient/index.js, src/pages/RecipeExploreMore/index.js, src/store/ducks/initialState.js, src/store/ducks/recipes/actions.js, src/store/ducks/recipes/reducers.js
=> [ GRUPO 16 ] BugFix

src/pages/TelaDetalheBebida/index.js, src/pages/TelaDetalheComida/index.js
=> feat: Implemented the requirement 41

src/pages/TelaDetalheBebida/index.js, src/pages/TelaDetalheComida/index.js
Reverts tryber/sd-07-project-recipes-app#991
=> Revert "feat: Implemented the requirement 41"

cypress/integration/explore_by_area_spec.js, src/pages/ExplorarBebidasArea/index.js, src/pages/index.js, src/routes/index.js
=> Main group 15 requirement 81
